version: "1.0"
project: "databricks-orchestrator"
updated: "2025-07-13"

# =============================================================================
# TASK MANAGEMENT INSTRUCTIONS
# =============================================================================
#
# This file contains ACTIVE and PENDING tasks only.
# Completed tasks should be moved to the appropriate archive file in completed/ (e.g., completed/2025-07.yaml)
#
# AUTOMATIC DATETIME GENERATION:
# CRITICAL FOR AI AGENTS: AI internal date perception is often WRONG - always use system datetime
# When creating or updating tasks, MUST run `date -Iseconds` command to get system time:
#   - created_date: Set when task is first created using `date -Iseconds`
#   - start_date: Set when status changes to "in_progress" using `date -Iseconds`
#   - completion_date: Set when status changes to "completed" using `date -Iseconds`
#
# STATUS MANAGEMENT:
# - pending → in_progress: Set start_date using `date -Iseconds` command (NOT AI internal date)
# - in_progress → completed: Set completion_date using `date -Iseconds` command and update actual_minutes
# - Any status → blocked: Add notes explaining the blocker
# - BEFORE marking completed: Ensure ALL test requirements are implemented and passing
#
# TEST REQUIREMENTS:
# - ALL tasks must include comprehensive test specifications
# - Unit tests REQUIRED for all code changes (95%+ coverage)
# - Integration tests REQUIRED for API/database changes
# - Performance/security tests REQUIRED when applicable
#
# TASK TEMPLATE: See .ai/templates/task-template.yaml for creating new tasks
#
# =============================================================================

tasks:
  - id: "INT-001"
    title: "AI Provider Integration Tests"
    status: "pending"
    priority: "medium"
    description: "Implement integration tests for multi-provider AI support, including provider failover, response validation, and error handling."
    dependencies: ["MVP-002"]
    estimated_minutes: 360

  - id: "DOC-001"
    title: "API Documentation Generation"
    status: "pending"
    priority: "medium"
    description: "Generate OpenAPI/Swagger documentation from FastAPI endpoints and create interactive API documentation."
    dependencies: ["API-001", "API-002"]
    estimated_minutes: 180

  - id: "PERF-001"
    title: "Database Query Optimization"
    status: "pending"
    priority: "low"
    description: "Optimize database queries for large datasets, implement proper indexing, and add query performance monitoring."
    dependencies: ["MVP-001"]
    estimated_minutes: 360

  - id: "SEC-001"
    title: "Authentication Implementation"
    status: "pending"
    priority: "medium"
    description: "Implement JWT-based authentication, user management, and API security middleware."
    dependencies: ["API-001"]
    estimated_minutes: 720

  - id: "UI-003"
    title: "Advanced UI Features"
    status: "pending"
    priority: "low"
    description: "Implement drag-and-drop task reordering, keyboard shortcuts, and advanced filtering options."
    dependencies: ["UI-001", "UI-002"]
    estimated_minutes: 600

  - id: "INTG-001"
    title: "Motion Integration"
    status: "pending"
    priority: "medium"
    description: "Complete Motion integration with bidirectional sync, real-time updates, and conflict resolution."
    dependencies: ["API-001"]
    estimated_minutes: 720

  - id: "INTG-002"
    title: "GitLab Integration"
    status: "pending"
    priority: "low"
    description: "Implement GitLab integration for issue tracking and project synchronization."
    dependencies: ["API-001", "INTG-001"]
    estimated_minutes: 600

  - id: "API-003"
    title: "WebSocket Support"
    status: "pending"
    priority: "medium"
    description: "Add WebSocket support for real-time updates, live collaboration, and push notifications."
    dependencies: ["API-001"]
    estimated_minutes: 480

  - id: "TEST-PERF-001"
    title: "Load Testing Suite"
    status: "pending"
    priority: "low"
    description: "Implement comprehensive load testing with Locust, including API endpoint stress tests and concurrent user simulations."
    dependencies: ["API-001", "API-002"]
    estimated_minutes: 360

  - id: "UI-004"
    title: "Dark Mode Support"
    status: "pending"
    priority: "low"
    description: "Implement dark mode theme with system preference detection and manual toggle."
    dependencies: ["UI-002"]
    estimated_minutes: 240

  - id: "DOC-002"
    title: "User Documentation"
    status: "pending"
    priority: "medium"
    description: "Create end-user documentation including getting started guide, feature tutorials, and video walkthroughs."
    dependencies: ["UI-001", "UI-002", "API-001"]
    estimated_minutes: 480

  - id: "DEL-010"
    title: "Add Alembic migration system"
    status: "completed"
    priority: "high"
    description: "Implement proper database migration system using Alembic with configuration, automation scripts, and comprehensive test suite."
    estimated_minutes: 240
    actual_minutes: 240
    start_date: "2025-07-15T11:09:33-07:00"
    completion_date: "2025-07-15T11:34:14-07:00"
    created_date: "2025-07-15T11:09:33-07:00"
    dependencies: ["DEL-006", "DEL-009"]
    test_requirements:
      unit_tests:
        - description: "Test Alembic configuration"
          files: ["backend/tests/test_migrations/test_alembic_config.py"]
          coverage_target: "100%"
          status: "completed"
        - description: "Test migration script generation"
          files: ["backend/tests/test_migrations/test_migration_generation.py"]
          coverage_target: "100%"
          status: "completed"
      integration_tests:
        - description: "Test migration upgrade and downgrade"
          files: ["backend/tests/test_migrations/test_migration_integration.py"]
          scope: "Complete migration lifecycle"
          status: "completed"
        - description: "Test migration with existing data"
          files: ["backend/tests/test_migrations/test_migration_data_safety.py"]
          scope: "Data preservation during schema changes"
          status: "completed"
      performance_tests:
        - description: "Test migration performance"
          files: ["backend/tests/test_migrations/test_migration_performance.py"]
          requirements: "< 10 seconds for typical migrations"
          status: "completed"
      security_tests:
        - description: "Test migration security"
          files: ["backend/tests/test_migrations/test_migration_security.py"]
          scope: "No data exposure during migrations"
          status: "completed"
    deliverables:
      - path: "backend/migrations/"
        type: "directory"
        description: "Alembic migration directory structure"
        status: "completed"
      - path: "backend/alembic.ini"
        type: "file"
        description: "Alembic configuration file"
        status: "completed"
      - path: "backend/migrations/versions/2025_07_15_1117-60f277eacf1c_initial_schema_migration.py"
        type: "file"
        description: "Initial migration from current schema"
        status: "completed"
      - path: "backend/scripts/migrate.py"
        type: "file"
        description: "Migration automation script"
        status: "completed"
      - path: "backend/src/setup/migration_manager.py"
        type: "file"
        description: "Migration manager for application startup"
        status: "completed"
    tags: ["database", "migrations", "schema", "alembic"]

summary:
  total_pending: 12
  high_priority: 0
  medium_priority: 6
  low_priority: 6
  total_estimated_minutes: 5220

next_sprint_recommendations:
  - "INT-001: AI Provider Integration Tests"
  - "DOC-001: API Documentation Generation"
