version: "1.0"
project: "databricks-orchestrator"
updated: "2025-07-13"

# =============================================================================
# TASK MANAGEMENT INSTRUCTIONS
# =============================================================================
#
# This file contains ACTIVE and PENDING tasks only.
# Completed tasks should be moved to the appropriate archive file in completed/ (e.g., completed/2025-07.yaml)
#
# AUTOMATIC DATETIME GENERATION:
# CRITICAL FOR AI AGENTS: AI internal date perception is often WRONG - always use system datetime
# When creating or updating tasks, MUST run `date -Iseconds` command to get system time:
#   - created_date: Set when task is first created using `date -Iseconds`
#   - start_date: Set when status changes to "in_progress" using `date -Iseconds`
#   - completion_date: Set when status changes to "completed" using `date -Iseconds`
#
# STATUS MANAGEMENT:
# - pending → in_progress: Set start_date using `date -Iseconds` command (NOT AI internal date)
# - in_progress → completed: Set completion_date using `date -Iseconds` command and update actual_hours
# - Any status → blocked: Add notes explaining the blocker
# - BEFORE marking completed: Ensure ALL test requirements are implemented and passing
#
# TEST REQUIREMENTS:
# - ALL tasks must include comprehensive test specifications
# - Unit tests REQUIRED for all code changes (95%+ coverage)
# - Integration tests REQUIRED for API/database changes
# - Performance/security tests REQUIRED when applicable
#
# TASK TEMPLATE: See .ai/templates/task-template.yaml for creating new tasks
#
# =============================================================================

tasks:
  - id: "TEST-API-002"
    title: "Test Suite: Orchestration Service Layer"
    status: "pending"
    priority: "high"
    description: "Implement comprehensive test suite for the orchestration service layer (ProjectService, TaskService, AgentService) including unit tests with mocked dependencies, integration tests with real storage and agents, and transaction handling across multiple operations."
    dependencies: ["API-001", "API-002"]
    estimated_hours: 6
    deliverables:
      - path: "backend/tests/test_services/test_project_service.py"
        type: "file"
        description: "Unit and integration tests for ProjectService"
        status: "pending"
      - path: "backend/tests/test_services/test_task_service.py"
        type: "file"
        description: "Unit and integration tests for TaskService"
        status: "pending"
      - path: "backend/tests/test_services/test_agent_service.py"
        type: "file"
        description: "Unit and integration tests for AgentService"
        status: "pending"
      - path: "backend/tests/test_services/test_service_transactions.py"
        type: "file"
        description: "Transaction and rollback behavior tests"
        status: "pending"

  - id: "TEST-UI-007"
    title: "Test Suite: Frontend-Backend Integration"
    status: "pending"
    priority: "high"
    description: "Implement integration tests between frontend and backend, including API service tests with mocked responses, hook tests with proper service mocking, and end-to-end tests for complete user workflows."
    dependencies: ["UI-001", "UI-002", "API-001"]
    estimated_hours: 8
    deliverables:
      - path: "frontend/src/services/__tests__"
        type: "directory"
        description: "API service layer tests"
        status: "pending"
      - path: "frontend/src/hooks/__tests__"
        type: "directory"
        description: "Hook integration tests"
        status: "pending"
      - path: "frontend/e2e"
        type: "directory"
        description: "End-to-end test suite"
        status: "pending"

  - id: "TEST-UI-002"
    title: "Test Suite: React Hook Testing"
    status: "pending"
    priority: "medium"
    description: "Implement comprehensive tests for custom React hooks including state management hooks, API integration hooks, and utility hooks."
    dependencies: ["UI-001"]
    estimated_hours: 4
    deliverables:
      - path: "frontend/src/hooks/useProjectManagement.test.ts"
        type: "file"
        description: "Tests for project management hook"
        status: "pending"
      - path: "frontend/src/hooks/useTaskOperations.test.ts"
        type: "file"
        description: "Tests for task operations hook"
        status: "pending"
      - path: "frontend/src/hooks/useLocalStorage.test.ts"
        type: "file"
        description: "Tests for local storage hook"
        status: "pending"


  - id: "INT-001"
    title: "AI Provider Integration Tests"
    status: "pending"
    priority: "medium"
    description: "Implement integration tests for multi-provider AI support, including provider failover, response validation, and error handling."
    dependencies: ["MVP-002"]
    estimated_hours: 6

  - id: "DOC-001"
    title: "API Documentation Generation"
    status: "pending"
    priority: "medium"
    description: "Generate OpenAPI/Swagger documentation from FastAPI endpoints and create interactive API documentation."
    dependencies: ["API-001", "API-002"]
    estimated_hours: 3

  - id: "PERF-001"
    title: "Database Query Optimization"
    status: "pending"
    priority: "low"
    description: "Optimize database queries for large datasets, implement proper indexing, and add query performance monitoring."
    dependencies: ["MVP-001"]
    estimated_hours: 6

  - id: "SEC-001"
    title: "Authentication Implementation"
    status: "pending"
    priority: "medium"
    description: "Implement JWT-based authentication, user management, and API security middleware."
    dependencies: ["API-001"]
    estimated_hours: 12

  - id: "UI-003"
    title: "Advanced UI Features"
    status: "pending"
    priority: "low"
    description: "Implement drag-and-drop task reordering, keyboard shortcuts, and advanced filtering options."
    dependencies: ["UI-001", "UI-002"]
    estimated_hours: 10

  - id: "INTG-001"
    title: "Motion Integration"
    status: "pending"
    priority: "medium"
    description: "Complete Motion integration with bidirectional sync, real-time updates, and conflict resolution."
    dependencies: ["API-001"]
    estimated_hours: 12

  - id: "INTG-002"
    title: "GitLab Integration"
    status: "pending"
    priority: "low"
    description: "Implement GitLab integration for issue tracking and project synchronization."
    dependencies: ["API-001", "INTG-001"]
    estimated_hours: 10

  - id: "API-003"
    title: "WebSocket Support"
    status: "pending"
    priority: "medium"
    description: "Add WebSocket support for real-time updates, live collaboration, and push notifications."
    dependencies: ["API-001"]
    estimated_hours: 8

  - id: "TEST-PERF-001"
    title: "Load Testing Suite"
    status: "pending"
    priority: "low"
    description: "Implement comprehensive load testing with Locust, including API endpoint stress tests and concurrent user simulations."
    dependencies: ["API-001", "API-002"]
    estimated_hours: 6

  - id: "UI-004"
    title: "Dark Mode Support"
    status: "pending"
    priority: "low"
    description: "Implement dark mode theme with system preference detection and manual toggle."
    dependencies: ["UI-002"]
    estimated_hours: 4

  - id: "DOC-002"
    title: "User Documentation"
    status: "pending"
    priority: "medium"
    description: "Create end-user documentation including getting started guide, feature tutorials, and video walkthroughs."
    dependencies: ["UI-001", "UI-002", "API-001"]
    estimated_hours: 8

summary:
  total_pending: 15
  high_priority: 3
  medium_priority: 7
  low_priority: 5
  total_estimated_hours: 105

next_sprint_recommendations:
  - "TEST-API-002: Service layer testing"
  - "TEST-UI-007: Frontend-backend integration"
