# AI Provider Configuration
providers:
  openai:
    models:
      - gpt-4
      - gpt-3.5-turbo
    default: gpt-4
    api_key_env: OPENAI_API_KEY
    
  anthropic:
    models:
      - claude-3-opus-20240229
      - claude-3-sonnet-20240229
    default: claude-3-opus-20240229
    api_key_env: ANTHROPIC_API_KEY
    
  gemini:
    models:
      - gemini-pro
    default: gemini-pro
    api_key_env: GEMINI_API_KEY
    
  xai:
    models:
      - grok-1
    default: grok-1
    api_key_env: XAI_API_KEY

# Task-specific model selection rules
selection_rules:
  planning:
    preferred: [anthropic, openai]
    model_preference: [claude-3-opus-20240229, gpt-4]
  
  decomposition:
    preferred: [openai, anthropic]
    model_preference: [gpt-4, claude-3-opus-20240229]
  
  editing:
    preferred: [anthropic, openai]
    model_preference: [claude-3-sonnet-20240229, gpt-3.5-turbo]